# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-LPR
version:      1.006
version_from: LPR.pm
installdirs:  site
requires:
    Carp:                          0
    IO::Socket:                    1
    IO::Socket::INET:              1
    Socket:                        1
    Sys::Hostname:                 1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
